### ISSUE TITLE
Installation/Run

### ISSUE THREAD

**Issue by gnomikos** [m-lab/ndt7-client-go#17]
Hello,
could you elaborate on how to install/run the client?

Many thanks,
George

**Comment by bassosimone** [comment]
Sure. I've written instructions in https://github.com/m-lab/ndt7-client-go/pull/18. When it's merged you will find them in the README. Until then, you find them at https://github.com/m-lab/ndt7-client-go/blob/feature/install_instructions/README.md (which will vanish after the merge).

**Comment by bassosimone** [comment]
I'm closing this issue now. Feel free to reopen if it does not work for you and you have questions. Thanks a bunch for your interest in this tool! :-)

**Comment by bassosimone** [comment]
Oh, I forgot to mention, once you have the binary, the README has a linking pointing out to a detailed description of the command line interface and the emitted output.

**Comment by bassosimone** [comment]
(Merged. Let us know if that's not working for you.)
