### ISSUE TITLE
upload: process counter-flow messages

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt7-client-go#23]
In https://github.com/m-lab/ndt-server/pull/148 I'm rewriting the upload path so that we also get counter-flow messages during the upload. This PR processes them and makes sure we return to the caller both server- and client-generated messages.

**Comment by bassosimone** [comment]
This is a P2 for me now, as we're currently fine with sender side measurements.

**Comment by robertodauria** [comment]
I believe this is now done: https://github.com/m-lab/ndt7-client-go/pull/38
