### ISSUE TITLE
Design reference summary stats

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt7-client-go#25]
A good question is whether this should be done also in `-batch` or not.

Reported by @critzo.

**Comment by critzo** [comment]
Currently using the `-batch` flag outputs JSON, but only interim results with no summary.

Running `ndt7-client` with no options returns what looks like a summary, but it's not clear:
```
$ ~/go/bin/ndt7-client 
download in progress with ndt-iupui-mlab4-iad04.measurement-lab.org
MaxBandwidth:    18.7 Mbit/s - RTT:    7/  29/   5 (min/smoothed/var) ms
download: complete
upload in progress with ndt-iupui-mlab4-iad04.measurement-lab.org
Avg. speed  :     4.9 Mbit/s
upload: complete
```

Running NDT from Measurement Kit provides some great summary values in its JSON output that would be helpful:
```
"advanced":{
   "avg_rtt":45.5651743754638,
   "congestion_limited":0.980206941298601,
   "fast_retran":7,
   "max_rtt":74,
   "min_rtt":13,
   "mss":1448,
   "out_of_order":0.0813636363636364,
   "packet_loss":0.000835721107927412,
   "receiver_limited":0.0,
   "sender_limited":0.0197930587013991,
   "timeouts":0},
"simple":{
   "download":9573.84748484385,
   "ping":13.0,
   "upload":9601.09205276634},
```
Measurement Kit also returns some helpful information as well, which would be useful:
```
"measurement_start_time":"2019-01-08 14:22:28"
"probe_asn":"AS7922"
```

A flag like `-summary` could be added to return an abbreviated summary in JSON for the completed test, perhaps containing:
```
   "client_IP":"<ipaddress>,
   "measurement_start_time":"2019-01-08 14:22:28"
   "probe_asn":"AS7922"
   "server":"ndt-iupui-mlab4-iad04.measurement-lab.org",
   "download":9573.84748484385,
   "ping":13.0,
   "upload":9601.09205276634
   "avg_rtt":45.5651743754638,
   "congestion_limited":0.980206941298601,
   "fast_retran":7,
   "max_rtt":74,
   "min_rtt":13,
   "mss":1448,
   "out_of_order":0.0813636363636364,
   "packet_loss":0.000835721107927412,
   "receiver_limited":0.0,
   "sender_limited":0.0197930587013991,
   "timeouts":0
```

**Comment by bassosimone** [comment]
We recently discussed with @pboothe that we are not doing this. We want the last message emitted by the test to be used for this purpose. It may require us to do some more work, perhaps in the server, to keep track of the max-max-bandwidth and min-min-rtt, perhaps. But we don't want to have to introduce a summary computation layer in clients.

**Comment by bassosimone** [comment]
Discussed with @mattmathis, we need to work on this

**Comment by bassosimone** [comment]
I believe https://github.com/m-lab/ndt-server/issues/194 is the best place where to do that.
