### ISSUE TITLE
add flag to enable client metadata to be set

### ISSUE THREAD

**Issue by critzo** [m-lab/ndt7-client-go#54]
Our JavaScript client code provides a way to set client metadata fields such as `clientApplication` or `clientOS` that is then stored in BigQuery. For example, for ndt5, these values can be found in:

```
measurement-lab.ndt.ndt5.result.Control.ClientMetadata.Name
measurement-lab.ndt.ndt5.result.Control.ClientMetadata.Value
```

Add a flag or other means for setting this metadata in `ndt7-client-go`

**Comment by stephen-soltesz** [comment]
@critzo can you clarify? Some of these values are collected automatically for ndt7-client-go already. https://github.com/m-lab/ndt7-client-go/blob/1addf1c64515bbc5cb3bfaaf4445d1cd687f9cf6/ndt7.go#L169-L174

do you also need a flag for arbitrary key/values?

**Comment by critzo** [comment]
As we discussed @stephen-soltesz arbitrary metadata values can be set using the locate URL. However, some existing ndt5 clients currently set some fields like client_name manually. Can these values be overridden? Where are these values saved in BigQuery? 

I think that if these are not to be overridden, then this issue should be about documenting how to set key/values within a client integration so that developers can set an identifier for their app.

**Comment by stephen-soltesz** [comment]
I don't understand yet.

These values are saved in the ndt7 `raw.Upload.ClientMetadata` and `raw.Download.ClientMetadata` records.

Do I understand correctly, that in addition to existing values, the requirement of this issue is one user-provided value for "application"?

**Comment by critzo** [comment]
Sorry if I'm not explaining this clearly.

* Current third party integrations of ndt5 set metadata like `client_os` or `client_name` to identify tests from their application in BigQuery. 
* To facilitate these clients migrating to ndt7, there should be a similar method of setting these values in `ndt7-client-go` and `ndt7-js`

Users should be able to set metadata values. We should document how we would like them to do this, or add a function that enables it if it's not enabled now.

Finally, @robertodauria and I were discussing this and think that client code should set metadata similarly. For example, are the values above set in a similar way by both `ndt7-client-go` and `ndt7-js`? We think there are some differences.

**Comment by robertodauria** [comment]
I think the general idea is that integrators would like to be able to distinguish measurements that were run from their integration even if they used one of our standard clients. They currently can, with ndt5, by setting the `clientApplication` field to something they can query for later.
Even if this field is sent to ndt-server by this client, it's not - I believe - currently configurable unless one changes the client's code.

**Comment by critzo** [comment]
@stephen-soltesz has suggested that client metadata could be specified using the `-locate.url` flag, with something like `-locate.url=https://locate.measurementlab.net/v2/nearest?client_application=<userdefinedString>`.

**Comment by robertodauria** [comment]
The `client_name` became configurable via a build flag, as documented in the README. (#71)

We agreed that making this "too easy" (i.e. with a command-line flag) would lead to a proliferation of spurious metadata values in BQ. This is, AFAICT, still an improvement over how one could do the same in ndt5-client (i.e. by changing the code).
