### ISSUE TITLE
Getting "websocket: bad handshake" response when using WS scheme 

### ISSUE THREAD

**Issue by Daemonslayer2048** [m-lab/ndt7-client-go#56]
I am getting the following error when using the go client:
```
    starting download
    download failed: websocket: bad handshake
    download: complete
    
    starting upload
    upload failed: websocket: bad handshake
    upload: complete
```
But if I use the default:
```
    starting download
    download in progress with ndt-iupui-mlab3-sea03.mlab-oti.measurement-lab.org
    
    Avg. speed  :     0.1 Mbit/s
    Avg. speed  :     0.1 Mbit/s
    Avg. speed  :     0.1 Mbit/s
    Avg. speed  :     0.1 Mbit/s
    Avg. speed  :     0.0 Mbit/s2020/10/23 10:55:15 ERROR: trafficshape: error on throttled read: read tcp 192.168.1.2:55008->173.205.3.37:443: i/o timeout
    
    download: complete
    
    starting upload
    upload in progress with ndt-iupui-mlab3-sea03.mlab-oti.measurement-lab.org
    
    Avg. speed  :     1.2 Mbit/s
    Avg. speed  :     1.1 Mbit/s
    Avg. speed  :     1.0 Mbit/s
    Avg. speed  :     0.9 Mbit/s
    Avg. speed  :     0.9 Mbit/s
    Avg. speed  :     0.9 Mbit/s
    Avg. speed  :     0.9 Mbit/s
    Avg. speed  :     0.8 Mbit/s
    Avg. speed  :     0.7 Mbit/s
    Avg. speed  :     0.6 Mbit/s
    Avg. speed  :     0.5 Mbit/s
    Avg. speed  :     0.3 Mbit/s2020/10/23 10:55:32 ERROR: trafficshape: failed write: write tcp 192.168.1.2:55014->173.205.3.37:443: i/o timeout
    2020/10/23 10:55:32 ERROR: trafficshape: failed write: write tcp 192.168.1.2:55014->173.205.3.37:443: i/o timeout
    
    upload: complete
             Server: ndt-iupui-mlab3-sea03.mlab-oti.measurement-lab.org
             Client: 
            Latency:     0.0 
           Download:     0.0 Mbit/s
             Upload:     0.3 Mbit/s
     Retransmission:    0.00
```
With the ARM devices I am using the WSS scheme yields significantly lower results. but this error has not been observed before. Is this possibly due to distance or speed?

**Comment by critzo** [comment]
@Daemonslayer2048 When using ARM devices with the go client, our recommendation is to use ARM64, not ARMv7 or ARMhf architectures, because armv7/hf does not have support for the cryptographic primitives needed to effectively use TLS (WSS). I expect this is the reason you are seeing slower measurement results. As for the other error you listed, perhaps others on the team will have additional insight.

**Comment by stephen-soltesz** [comment]
@Daemonslayer2048 please share the complete command line. From the error messages it looks like you're using the ndt5-client `-throttle` flag, which is not supported in ndt7-client. Can you help clarify your setup?

**Comment by natedogith1** [comment]
I'm also seeing this issues with "websocket: bad handshake"
```
~$ ./go/bin/ndt7-client
download in progress with ndt-mlab1-iad06.mlab-oti.measurement-lab.org
Avg. speed  :    86.4 Mbit/s
download: complete
upload in progress with ndt-mlab1-iad06.mlab-oti.measurement-lab.org
Avg. speed  :    12.8 Mbit/s
upload: complete
         Server: ndt-mlab1-iad06.mlab-oti.measurement-lab.org
         Client: <removed>
        Latency:    26.6 ms
       Download:    86.4 Mbit/s
         Upload:    12.8 Mbit/s
 Retransmission:    4.48 %
```
explicitly specifying the same server that was selected in the previous run:
```
$ ./go/bin/ndt7-client -server=ndt-mlab1-iad06.mlab-oti.measurement-lab.org
download failed: websocket: bad handshake

download: complete
upload failed: websocket: bad handshake

upload: complete
```

**Comment by stephen-soltesz** [comment]
@natedogith1 M-Lab deployment of the ndt-server no longer supports direct server measurements for ndt7. ndt7 on M-Lab now requires using the Locate v2 API, which issues access tokens. The default mode for ndt7-client is to use the Locate v2 API to discover a near by server.

This change is due in part to poor scheduling by a significant population of clients targeting specific servers. While specific M-Lab servers are no longer supported, the ndt7-client supports location selection by country or region. See examples in: https://github.com/m-lab/locate/blob/master/USAGE.md#how-gcp-identifies-client-location

**Comment by stephen-soltesz** [comment]
Closing this issue as "wont fix" because direct targeting of M-Lab servers is no longer supported.
