### ISSUE TITLE
Randomize the payload when using cleartext WebSocket

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt7-client-go#61]
See https://github.com/m-lab/ndt-server/issues/332

**Comment by nosnilmot** [comment]
Similar to my comment on https://github.com/m-lab/ndt-server/issues/332#issuecomment-860612491, isn't the client also already using random data [here](https://github.com/m-lab/ndt7-client-go/blob/master/internal/upload/upload.go#L18) ?

**Comment by robertodauria** [comment]
The client sends a random payload already.
