### ISSUE TITLE
Add support for updating the version number

### ISSUE THREAD

**Issue by bassosimone** [m-lab/ndt7-client-go#7]
Currently it's hardcoded. To be done after #4 is merged.

**Comment by pboothe** [comment]
We should talk about this. It's kind of tricky at a semantic level.

**Comment by bassosimone** [comment]
I am also starting to think this may be over-engineering it. Am I?

**Comment by pboothe** [comment]
It is very easy to overengineer something like this.  I am perfectly happy just leaving in the github commit hash and calling it a day.
