### ISSUE TITLE
A pure upload test does not report latency

### ISSUE THREAD

**Issue by dtaht** [m-lab/ndt7-client-go#80]
davet@milliways:~/git/ndt7-client-go$ ./ndt7-client -download=false & 
[1] 2045136
upload in progress with ndt-mlab1-lax02.mlab-oti.measurement-lab.org
Avg. speed  :     4.3 Mbit/s
upload: complete
         Server: ndt-mlab1-lax02.mlab-oti.measurement-lab.org
         Client: 
        Latency:     0.0 
       Download:     0.0 Mbit/s
         Upload:     4.3 Mbit/s
 Retransmission:    0.00

**Comment by robertodauria** [comment]
Thanks for reporting it! This should have been fixed by #82.
